### PR TITLE
docs: develop steps

### PR DESCRIPTION
**Pull request by rudy-xhd**
### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following
- [x] Read the [Contributing Guidelines](https://devtools.vuejs.org/guide/contributing.html).
- [x] Read the [Pull Request Guidelines](https://devtools.vuejs.org/guide/contributing.html#pull-request-guidelines) and follow the [Commit Convention](https://github.com/vuejs/devtools/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by Akryum** [comment]
Why this change? :thinking:

**Comment by rudy-xhd** [comment]
hello @Akryum. 
I'm interested in contributing to the Vue devtools, but the contributing guide make me confused. 
`yarn install` can't install the deps in the `packages` directory. Then run `yarn run build:watch` will throw some error.

**Comment by Akryum** [comment]
Yarn is supposed to install dependencies in the packages, we don't use lerna for this. What are the errors?

**Comment by rudy-xhd** [comment]
Oh, I can't reproduce the error. Sorry to bother you.

**Pull request closed without merging**
