### PR TITLE
fix: remove redundant console.log

### PR DESCRIPTION
**Pull request by bgoscinski**
Fixes https://github.com/vuejs/devtools/issues/1567

### CODE REVIEW

**Comment by jmartinsen** [comment]
Please merge asap. This is painful.

**Comment by Grawl** [comment]
it hurts me please merge it

**Comment by bgoscinski** [comment]
I'm not a maintainer in this repo so we have to wait for someone from the core team (@Akryum) to merge this. 
I'm also affected by this so I share your frustration but please refrain from commenting here unless you're reviewing this PR. Thanks

**Comment by antony-k1208** [comment]
We need a new tag for this to finally get rid of the debug output, right?

**Comment by qwexvf** [comment]
This is causing my browser to crush. can you please make a release for this?

**Pull request merged**
