### PR TITLE
fix: `store.replaceState` could be undefined at init hook

### PR DESCRIPTION
**Pull request by JounQin**
found this issue when visiting https://h5.m.taobao.com/taolive/video.html?id=247286524761&livesource=shop&spm=a2141.7631565.homelive_-1576063041731.0

image

### CODE REVIEW

**Comment by JounQin** [comment]
@Akryum Would you like to review this PR?

**Comment by JounQin** [comment]
@Akryum Again?

**Comment by JounQin** [comment]
@posva @yyx990803 Can you take a look?...

**Comment by posva** [comment]
Wait for @Akryum review, he will come when he can. Also, you should provide a repro of the bug or add a test that fails without the fix

**Comment by Akryum** [comment]
A test could be nice :+1:

**Comment by JounQin** [comment]
> you should provide a repro of the bug

I did provide an online reproduction and error capture in the issue description. It's clear how to fix it quickly but I don't have more time to figure out why it happened.

**Comment by JounQin** [comment]
@Akryum Can we get this PR merged or should I close it?
I'm not the developer of the original site, it could be a compatibility issue.
Since I don't have the whole source code, so I could not provide how to reproduce it with a non-production version.

**Pull request closed without merging**
