### PR TITLE
docs: Plugins Guide grammar

### PR DESCRIPTION
**Pull request by king-11**
grammar correction in sentence

### CODE REVIEW

**Comment by Akryum** [comment]
Thanks! Isn't technically "devtools" plural?

**Comment by king-11** [comment]
If we think of the extension panel it's a single entity so  using `is` seemed more apt to me considering we are talking about a single entity that user is interacting with. But I can make the change if you feel we should use `is` 😅

**Comment by Akryum** [comment]
I've been using `are` in the rest of the docs so I guess we should stick to it or change it everywhere 😅

**Comment by king-11** [comment]
Made the changes for `are`

**Pull request merged**
